import Cocoa

/// Payload of a clipboard entry: either plain text or an image (stored as
/// PNG data, since that's compact and trivially reloadable into NSImage).
enum ClipboardContent: Equatable {
    case text(String)
    case image(Data)
}

struct ClipboardEntry: Equatable, Identifiable {
    let id: UUID
    let content: ClipboardContent
    let date: Date

    init(content: ClipboardContent, date: Date = Date()) {
        self.id = UUID()
        self.content = content
        self.date = date
    }
}

class ClipboardHistoryManager {

    static let shared = ClipboardHistoryManager()

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int

    // All history (text and image entries mixed, newest first)
    private(set) var items: [ClipboardEntry] = []

    // Pinned entries, tracked by stable entry ID rather than content —
    // content-based pinning (the old `Set<String>`) only ever worked for
    // text and would have broken once image entries were added.
    private(set) var pinnedIDs: Set<UUID> = []

    // Limits
    // Text limit is user-configurable via Settings (see SettingsManager).
    var maxStoredItems: Int {
        max(1, min(20, SettingsManager.shared.historyLimit))
    }
    // Images are capped separately and lower, since each one is much larger
    // than a text entry and there's no user-facing setting for it (yet).
    let maxStoredImages = 5
    let maxVisiblePinned = 5          // How many pinned items to show in menu

    private init() {
        lastChangeCount = pasteboard.changeCount
        startMonitoring()
    }

    private func startMonitoring() {
        Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.checkPasteboard()
        }
    }

    // Informal but widely-adopted convention (used by 1Password, Bitwarden,
    // and most other password managers) for marking a pasteboard write as
    // sensitive/transient, specifically so clipboard managers skip it.
    // See https://nspasteboard.org
    private static let sensitiveContentTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    private func checkPasteboard() {
        let currentChangeCount = pasteboard.changeCount
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount

        if let types = pasteboard.types,
           types.contains(where: Self.sensitiveContentTypes.contains) {
            NSLog("🔒 Skipping clipboard entry marked as sensitive/transient")
            return
        }

        // Check for an image first. Some apps put both an image and a
        // string (e.g. a file path) on the pasteboard when you copy a
        // picture, and the image is what the user actually cares about.
        if let imageData = readImageData() {
            addEntry(.image(imageData))
            return
        }

        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            addEntry(.text(string))
        }
    }

    /// Reads an image off the pasteboard, if present, normalized to PNG data.
    private func readImageData() -> Data? {
        // FIX: Finder's "Copy" of an image FILE puts a file URL on the
        // pasteboard, plus a generic-icon TIFF that isn't the real image —
        // that's why a copied file showed a wrong/blurry thumbnail while
        // copying actual image content (e.g. Preview's Copy, or an image
        // from a web page) worked fine. When a file URL is present and
        // points at an image, read the real bytes from disk instead of
        // trusting whatever preview TIFF the pasteboard carries.
        if let fileURLs = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           let url = fileURLs.first,
           isImageFile(url),
           let fileData = try? Data(contentsOf: url) {
            return normalizedPNGData(from: fileData)
        }

        // Otherwise, this is actual image data placed directly on the
        // pasteboard (not a reference to a file on disk).
        guard let types = pasteboard.types, types.contains(.tiff) || types.contains(.png) else {
            return nil
        }

        if let pngData = pasteboard.data(forType: .png) {
            return pngData
        }

        if let tiffData = pasteboard.data(forType: .tiff) {
            return normalizedPNGData(from: tiffData)
        }

        return nil
    }

    private func isImageFile(_ url: URL) -> Bool {
        let imageExtensions: Set<String> = ["png", "jpg", "jpeg", "gif", "tiff", "tif", "bmp", "heic", "heif", "webp"]
        return imageExtensions.contains(url.pathExtension.lowercased())
    }

    /// Converts raw image data to PNG unless it already is PNG.
    private func normalizedPNGData(from data: Data) -> Data? {
        let pngSignature: [UInt8] = [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]
        if data.starts(with: pngSignature) {
            return data
        }
        guard let bitmap = NSBitmapImageRep(data: data) else { return data }
        return bitmap.representation(using: .png, properties: [:]) ?? data
    }

    private func addEntry(_ content: ClipboardContent) {
        // Remove duplicate if exists (same text, or byte-identical image)
        if let existingIndex = items.firstIndex(where: { $0.content == content }) {
            items.remove(at: existingIndex)
        }

        let entry = ClipboardEntry(content: content)
        items.insert(entry, at: 0)

        trim()

        NotificationCenter.default.post(name: .clipboardDidUpdate, object: nil)
    }

    /// Trims text and image entries down to their respective caps
    /// independently, so a burst of copied images doesn't push out all the
    /// text history (or vice versa).
    private func trim() {
        var textSeen = 0
        var imageSeen = 0
        var indicesToRemove: [Int] = []

        for (index, entry) in items.enumerated() {
            switch entry.content {
            case .text:
                textSeen += 1
                if textSeen > maxStoredItems {
                    indicesToRemove.append(index)
                }
            case .image:
                imageSeen += 1
                if imageSeen > maxStoredImages {
                    indicesToRemove.append(index)
                }
            }
        }

        for index in indicesToRemove.sorted(by: >) {
            items.remove(at: index)
        }
    }

    // ====== PUBLIC METHODS FOR MENU ======

    /// Legacy method that simply returns recent items (if still called somewhere)
    func visibleItems() -> [ClipboardEntry] {
        return visibleRecentItems()
    }

    /// Items for Recent block (without pinned)
    func visibleRecentItems() -> [ClipboardEntry] {
        items.filter { !pinnedIDs.contains($0.id) }
    }

    /// Items for Pinned block (only pinned items that still exist in items)
    func visiblePinnedItems() -> [ClipboardEntry] {
        let pinned = items.filter { pinnedIDs.contains($0.id) }
        return Array(pinned.prefix(maxVisiblePinned))
    }

    func isPinned(_ entry: ClipboardEntry) -> Bool {
        pinnedIDs.contains(entry.id)
    }

    func togglePin(for entry: ClipboardEntry) {
        if pinnedIDs.contains(entry.id) {
            pinnedIDs.remove(entry.id)
        } else {
            pinnedIDs.insert(entry.id)
        }

        NotificationCenter.default.post(name: .clipboardDidUpdate, object: nil)
    }

    /// FIX: changing "History Limit" in Settings wrote the new value to
    /// SettingsManager, but nothing ever re-ran trim() or refreshed the
    /// menu with it — trim() only ran as a side effect of the *next*
    /// clipboard copy, so lowering the limit visibly did nothing until you
    /// copied something new (and raising it did nothing at all, since there
    /// was nothing to trim). Settings now calls this right after the value
    /// changes, so the stored/visible list matches the new limit immediately.
    func applyHistoryLimitChange() {
        trim()
        NotificationCenter.default.post(name: .clipboardDidUpdate, object: nil)
    }
}

extension Notification.Name {
    static let clipboardDidUpdate = Notification.Name("clipboardDidUpdate")
}
